baseURL: ""
languageCode: en-us
title: Furkan Ercevik
theme: PaperMod

params:
  
  cover:
    linkFullimages: true

  ShowBreadCrumbs: true
  ShowReadingTime: true
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 5
    - identifier: projects
      name: Projects
      url: /projects
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags
      weight: 20

deployment:
  targets:
    name: "mydeployment"
    URL: "s3://fercevik.com?region=us-west-1"